name: example
description: "ShoppApp UI Kit Example App."
publish_to: 'none'  # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8 
  shopapp_widgets:  
    path: ../
  auto_route: ^9.3.0+1
  supabase_flutter: ^2.8.2
  dio: ^5.0.0
  retrofit: ^4.4.2
  json_annotation: ^4.6.0
  json_serializable: ^6.6.0
  intl: ^0.19.0
  shared_preferences: ^2.5.2 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  flutter_gen_runner: 
  retrofit_generator: ^9.1.9
  auto_route_generator: ^9.0.0
  flutter_launcher_icons: ^0.14.3


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/logo_background.png"


flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  integrations:
    image: true
    flutter_svg: true

flutter:
  uses-material-design: true
  assets:
    - assets/env/.env
    - .env
    - assets/images/
    - assets/icons/
    - assets/mapstyle/
