name: shopapp_widgets
description: "A new Flutter package project."
version: 1.0.0


environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  smooth_page_indicator: ^1.2.0+3
  simple_ripple_animation: ^0.1.0
  loading_animation_widget: ^1.3.0
  font_awesome_flutter: ^10.8.0
  flutter_otp_text_field: ^1.4.0+2
  device_preview: ^1.2.0
  flutter_svg: ^2.0.10  
  flutter_typeahead: ^4.0.0
  flutter_dotenv: ^5.0.2
  u_credit_card: ^1.2.1
  google_maps_flutter: ^2.10.1
  lint: ^1.0.0
  firebase_core: 
  firebase_messaging: 
  onesignal_flutter: ^5.1.2
  firebase_auth: 
  google_sign_in: ^5.2.1
 


  

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  
  

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
# flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package